name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint codebase
        run: npm run lint

      - name: Check type
        run: npm run lint:tsc

      - name: Run tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # action should work on a clean machine without building
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [LATEST, 15.21.0, 14.14.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run action
        uses: ./

      - name: Run action with inputs
        uses: ./
        with:
          butler-version: ${{ matrix.version }}
          cli-name: butler

      - name: Locate binary
        run: command -v butler

      - name: Check version
        if: matrix.version != 'LATEST'
        shell: bash
        run: |
          butler --version &> BUTLER_VERSION
          if [[ $(cat BUTLER_VERSION) != *'${{ matrix.version }}'* ]]; then
            echo 'Version does not match. See version below:'
            butler --version
            exit 1
          fi

      - name: Show help
        run: butler --help
